### ISSUE TITLE
Collision check on heightmap not working properly.

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/emc_simulator#10]
With the current implementation the collision check finds more collisions than there are in actuality. 

Intuitively if one has a round robot with radius 0.2 then 
`collision = heightmap->intersect(robot_pose.t, 0.2)` 
should indicate a collision with the heightmap. In actuality it finds collisions with a radius larger than this 0.2 in the simulator. 

Unknown if this is a bug in the simulator's construction of the heightmap or in geolib's implementation of the intersect function for composite shapes.

**Comment by KdVos** [comment]
I've created a simplified example of the bug described above:

Let's start with a (shortened) snippet of the code (full version found here)

```
int main(int argc, char **argv)
{
    // find the heightmap
    std::string heightmap_filename;
    heightmap_filename = ros::package::getPath("emc_simulator") + "/data/heightmap_correct.pgm";

   // robot position at the center of the image
    geo::Vector3 rpose; = (0,0,0);
    std::cout<<rpose<<std::endl;

   // Process the heightmap image
    std::vector<Door> doors;
    geo::ShapePtr heightmap = createHeightMapShape(heightmap_filename, doors);

   // Loop over distances
    for (int i = 0; i < 100; i++)
    {
        double dist = 0.15 + i * 0.004;
       // check for intersection
        bool test = heightmap->intersect(rpose,dist);
 
        if (test)
        {
            std::cout<< "Dist " << dist <<" Collision" <<std::endl;
        }
        else
        {
            std::cout<< "Dist " << dist <<" NO Collision"<<std::endl;
        }
    }   
}
```
To briefly describe the inteded working of the code. A file is loaded in as a heightmap. The robot is positioned at (0,0,0). The robot is inflated, for every robot size it is detected whether a collision occurs. This is also wirtten to the terminal.

If we now consider the hospital heightmap used by the simulator:
![This is an image](https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/data/heightmap.pgm)

The inteded behaviour is a collision detected at a radius of approx. 0.45 m, since the distance between the point (0,0,0) and the right wall of the corridor is equal to 18 pixels. The observed behaviour is that the collision already occurs at a radius of approx. 0.18 m.

**Comment by KdVos** [comment]
However, if we now remove everything **but** the wall that is supposed to cause the collision, the observed behavior **is** correct

![This is an image](https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/data/heightmap_correct.pgm)

The same holds for the following heightmap

![This is an image](https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/data/heightmap_correct2.pgm)

**Comment by KdVos** [comment]
More bizarrely the code **doesn't** work correctly for the following examples

![This is an image](https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/data/heightmaptest_incorrect.pgm)


![This is an image](https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/data/heightmaptest_incorrect2.pgm)


![This is an image](https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/data/heightmaptest_incorrect3.pgm)

**Comment by KdVos** [comment]
For clarity, the dimensions of all images are the same. The (approximate) location of (0,0,0) is denoted in red in the image below.
![heightmap_red](https://user-images.githubusercontent.com/50488480/164730370-b3d8887b-2846-4233-b7cc-49be3d3560c5.png)

**Comment by MatthijsBurgh** [comment]
> Let's start with a (shortened) snippet of the code (full version found here)

Where?

**Comment by MatthijsBurgh** [comment]
The heightmap is converted to a mesh. So I suggest you create a test which just loads the heightmap and exports it to a file.

**Comment by KdVos** [comment]
> > Let's start with a (shortened) snippet of the code (full version found here)
> 
> Where?

Sorry forgot the insert the link:

[https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/src/testcase.cpp]()

**Comment by KdVos** [comment]
A further clarification for someone coming across this issue. The current collision detection implementation used in the simulator works as expected, at least in the limited testing that was done in the preperation for the MRC course.

However, in order to get it working we made use of the lrf sensor implementation. The current simulator does **not** make use of the intersect function described in the issue above. However, this doesn't mean it isn't of interest to investigate where the issue above originates, whether it is in the creation of the heightmap or in geolib.

**Comment by KdVos** [comment]
> So you can check it visually in mesh viewer.

Done. Follow the links below to inspect the meshes of three of the examples. I can't seem to identify the problem

[Correct result](https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/data/heightmap_correct.stl)
[Incorrect result 1](https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/data/heightmap.stl)
[Incorrect result 2](https://github.com/tue-robotics/emc_simulator/blob/bug/collisiondetection/data/heightmaptest_incorrect.stl)

If all is well you should be able to view the stl files in the github interface. Otherwise I'll provide some pictures.

**Comment by KdVos** [comment]
- [ ] Verified correct working of the collision check in the bug branch of the simulator, given the updated geolib

**Comment by KdVos** [comment]
@PetervDooren Maybe you can use the code in the top message

**Comment by MatthijsBurgh** [comment]
Does the incorrect STL files only apply to the collision checking or also the laser rendering?
