### ISSUE TITLE
multirobot simulation

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/emc_simulator#4]
Idea was discussed to have the final challenge simulate two robots. Each running their own software. This is a list of the changes that need to be made to the software to allow that.

- [x] simulator
    - [x] move functionality to robot cpp object
        - [x] publishers subscribers
        - [x] virtualbase
        - [x] lrf
        - [x] make robot name configurable 'pico'/'taco'
   - [x] loop over robot objects for
       - [x] motion
       - [x] lrf data generation
       - [x] Make other robots show up in lrf data
       - [x] visualisation
   - [x] add multibot config to simulator
- [x] emc system (solution to most of these will be a name parameter with default 'pico')
    - [x] Allow remapping to certain topics without requiring students to change their code
    - [x] Allow  multibot approach to emc-viz
    - [x] Allow multibot approach to pico-teleop

**Comment by MatthijsBurgh** [comment]
multirobot approach for pico-teleop and emc-viz should just be different aliases IMO.

I don't know if looping over multiple robots is the correct approach. Multi threading sounds like the better solution to me for performance. But this is also the more complex solution.

Also important thing is that the robots show up in each other sensors.

**Comment by bobhendrikx** [comment]
Nice list peter, i see you started implementation. 
I think we need a way to configure the simulator for dual robots. Could be just via the config file. 
We also need a way to remap the student executable topics. They are running as ROS nodes via the EMC wrapper i think, so that should probably be straightforward. 
But do keep in mind that some students will have different launch workflows, such as launch files and navigation stacks. 
my point here being: do we want to run two separate navigation stacks, given that they would lead to interfering topics internal to their strategy, and the CPU we run it on might not like it very much.

@MatthijsBurgh I think multithreading wouldnt provide much benefit, as we would have to synchronize the threads to update the simulator anyway, but i might be wrong. 

@PetervDooren If you want to explore this i think it is nice! We can always resort back to the original simuator if for any reasons it appears to be a bad idea. But do keep in mind that there are some pitfalls and time is short, before you invest too much time in it :)

**Comment by MatthijsBurgh** [comment]
@bobhendrikx you can calculate the updates of multiple robots at the same time. Each update should be independent of the other robot(s), so can be applied when ready. Then the thread has to wait. Either it needs to be triggered again by the main thread. Or you could use an [std::barrier](https://en.cppreference.com/w/cpp/thread/barrier), to let the threads wait until they both(can be more than 2) reached that barrier.

**Comment by PetervDooren** [comment]
Multithreading wont be necessary as it wont add anything. The time investment is a bigger issue. I guesstimate this might be a full days work.

Groups using ros wont have trouble switching the robots namespace. I wonder whether or not we can remap topics when their executable is not run through rosrun/roslaunch. I could imagine running the executable with an extra parameter like ./doyourthing pico 2 3 4

**Comment by MatthijsBurgh** [comment]
yes remapping should work even when rosrun/roslaunch is not used

**Comment by MatthijsBurgh** [comment]
Multithreading will increase the performance as you are doing things in parallel instead of all serial.
